services:
  robot_1:
    container_name: robot_1
    image: gocas/robot_1:latest
    build: .
    environment:
      - ROBOT_NAME=robot1
      - ROBOT_SERIAL_NUMBER=${ROBOT_1_SERIAL_NUMBER}
    ports:
      - "8001:8000"  # Map the webserver port from the container to the host
    restart: always
    privileged: true
    volumes:
      - /dev:/dev
      - .:/app

  robot_2:
    container_name: robot_2
    image: gocas/robot_2:latest
    build: .
    environment:
      - ROBOT_NAME=robot2
      - ROBOT_SERIAL_NUMBER=${ROBOT_2_SERIAL_NUMBER}
    ports:
      - "8002:8000"  # Map the webserver port from the container to the host
    restart: always
    privileged: true
    volumes:
      - /dev:/dev
      - .:/app

  robot_3:
    container_name: robot_3
    image: gocas/robot_3:latest
    build: .
    environment:
      - ROBOT_NAME=robot3
      - ROBOT_SERIAL_NUMBER=${ROBOT_3_SERIAL_NUMBER}
    ports:
      - "8003:8000"  # Map the webserver port from the container to the host
    restart: always
    privileged: true
    volumes:
      - /dev:/dev
      - .:/app