services:
  robot_1:
    build: .
    environment:
      - ROBOT_NAME=robot1
      - ROBOT_SERIAL_NUMBER=123456
    ports:
      - "8001:8000"  # Map the webserver port from the container to the host
    restart: always
    privileged: true
    devices:
      - "/dev/ttyUSB_robot1:/dev/ttyUSB_robot1"  # Pass through the USB device
  robot_2:
    build: .
    environment:
      - ROBOT_NAME=robot2
      - ROBOT_SERIAL_NUMBER=123456
    ports:
      - "8002:8000"  # Map the webserver port from the container to the host
    restart: always
    privileged: true
    volumes:
      - /dev:/dev
      - .:/app

  robot_3:
    build: .
    environment:
      - ROBOT_NAME=robot3
      - ROBOT_SERIAL_NUMBER=123456
    ports:
      - "8003:8000"  # Map the webserver port from the container to the host
    restart: always
    privileged: true
    devices:
      - "/dev/ttyUSB_robot3:/dev/ttyUSB_robot3"  # Pass through the USB device